#Makefile for cleaning examples directory

clean:
	rm -rf  *.tmp  *.log  log transcript work *.wlf vsim.fcdb *stacktrace*
	rm -rf *~ core csrc simv* vc_hdrs.h ucli.key urg* *.log core.*
	rm -rf DVEfiles inter.vpd

